SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS setting;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS user_contract;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS entry_type;
DROP TABLE IF EXISTS entry_activity;
DROP TABLE IF EXISTS entry;

SET FOREIGN_KEY_CHECKS = 1;